version: 1.3.6-BUILD{build}
image: Visual Studio 2015
before_build:
- nuget restore
xamarin:
  email: erikjan_dewit@hotmail.com
  password:
    secure: yNLXq7p6mLuCZnpQVfGOlg==
  android: true
  ios: true
build:
  verbosity: normal
  project: FHSDK.sln
test: off